sudo: false

language: ruby

addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-xetex
    - texlive-publishers

rvm:
- 1.9.3

script: /bin/bash gh-publisher-scripts/gh-publisher.sh
